"use client";

import Header from "@components/Header/Header";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
import "../styles/globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";
import { useState } from "react";
const pjs = Plus_Jakarta_Sans({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [hamOpen, setHamOpen] = useState(false);

  return (
    <html lang="en" className={pjs.className}>
      <body className="body">
        <Header hamOpen={hamOpen} setHamOpen={setHamOpen} />
        {children}
      </body>
    </html>
  );
}
